### ISSUE TITLE
Problem when refreshing caches

### ISSUE THREAD

**Issue by hostep** [reinos/Magento-AdaptiveResize#1]
Hello

We just started using your extension which works great, but when we try to refresh the caches through Cache Management in the Magento backend.
We get this error:

```
a:5:{i:0;s:69:"Mage registry key "_singleton/adaptiveresize/observer" already exists";i:1;s:1321:"#0 app/Mage.php(223): Mage::throwException('Mage registry k...')
#1 app/Mage.php(477): Mage::register('_singleton/adap...', false)
#2 app/code/core/Mage/Core/Model/App.php(1316): Mage::getSingleton('adaptiveresize/...')
#3 app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('adminhtml_cache...', Array)
#4 app/code/core/Mage/Adminhtml/controllers/CacheController.php(128): Mage::dispatchEvent('adminhtml_cache...', Array)
#5 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_CacheController->massRefreshAction()
#6 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('massRefresh')
#7 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#9 app/Mage.php(684): Mage_Core_Model_App->run(Array)
#10 index.php(87): Mage::run('', 'store')
#11 {main}";s:3:"url";s:78:"/index.php/admin/admin/cache/massRefresh/key/13d84b33998b149d8d5163df889fff3c/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}
```

Can you take a look at what might be going on?

Thanks!

**Comment by ktsixit** [comment]
I have the same problem. Did you find a solution?

**Comment by hostep** [comment]
I think we switched to another library due to this problem, if I remember correctly it was this one: https://github.com/obukhow/AdaptiveResize
